/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example

fun main() {
    val ENVIRONMENT = System.getenv("ENVIRONMENT")
    val SOME_ENV = System.getenv("SOME_ENV")

    println("I'm running in $ENVIRONMENT environment")
    println("SOME_ENV is '$SOME_ENV'")
}
